# Dockerfile for the Free Tier Flask application.
#
# This Dockerfile builds a minimal container image for running the Flask API
# that launches Kubernetes jobs. It installs the required dependencies and
# copies the application code into the image. 
# Students may modify this file to add build steps or change the base image as needed.


# TODO: Specify a Python base image
FROM python:3.6

# TODO: Set the working directory
WORKDIR /app

# TODO: Copy the necessary application files into the image (from free_service/app/ directory)
COPY free_service/app/flask_app.py /app/
COPY free_service/app/requirements_flaskapp.txt /app/


# TODO: Install Python dependencies
RUN pip install --no-cache-dir -r requirements_flaskapp.txt


# TODO: Expose the required port
EXPOSE 5000

# Specify the default command to run the Flask app
CMD ["python3", "flask_app.py"]