#
# This YAML defines a template for launching a batch job in the 'free-service' namespace.
# The job runs a container that performs a classification task.
#
# TODO: Fill in the Kubernetes Job spec here.

apiVersion: batch/v1
kind: Job
metadata:
  name: free-tier-job
  namespace: free-service
spec:
  template:
    spec:
      containers:
      - name: classifier
        image: vkadam157/free-tier-job:latest
        imagePullPolicy: Always
        command: ["python", "classify.py"]
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"
      restartPolicy: Never
  backoffLimit: 4
